---
apiVersion: actions.summerwind.dev/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: actions-runner
  namespace: actions-runner-system
spec:
  githubConfigUrl: rtm-org/hng_boilerplate_expressjs
  githubConfigSecret: runner-controller-manager
  minRunners: 0
  maxRunners: 20
