# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: runner-system
#   labels:
#     name: runner-system

---
apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: actions-runner
  namespace: actions-runner-system
spec:
  githubConfigUrl: rtm-org/hng_boilerplate_expressjs
  githubConfigSecret: runner-controller-manager
  minRunners: 0
  maxRunners: 20
  template:
    spec:
      containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        env:
        - name: RUNNER_ALLOW_RUNASROOT
          value: "1"
        - name: RUNNER_MANUALLY_TRAP_SIG
          value: "true"
        command: ["/runner/run.sh"]
        volumeMounts:
        - name: runner
          mountPath: /runner
      initContainers:
        - name: setup
          image: ghcr.io/actions/actions-runner:latest
          command: ["sh", "-c", "cp -r /actions-runner/* /runner/"]
          volumeMounts:
          - name: runner
            mountPath: /runner
      volumes:
        - name: runner
          emptyDir: {}
