githubConfigUrl: "https://github.com/rtm-org/hng_boilerplate_expressjs"
githubConfigSecret: runner-controller-manager
maxRunners: 20
minRunners: 0
runnerScaleSetName: "hng-ubuntu-runners"
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]