name: Deploy Manifests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Kubectl CLI
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Set Kubeconfig Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Fetch Cluster Details
        run: |
          kubectl version
          echo ----------------------------------------------------
          kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.3

      - name: Check Helm Version
        run: helm version

      - name: Create Namespace
        run: |
          kubectl get namespace ${{ vars.NAMESPACE }} || kubectl create namespace ${{ vars.NAMESPACE }}

      - name: Register GitHub App Info as Secret
        run: |
          kubectl get secret runner-controller-manager --namespace=${{ vars.NAMESPACE }} && \
          kubectl delete secret runner-controller-manager --namespace=${{ vars.NAMESPACE }}

          kubectl create secret generic runner-controller-manager \
            --namespace=${{ vars.NAMESPACE }} \
            --from-literal=github_app_id=${{ secrets.APP_ID }} \
            --from-literal=github_app_installation_id=${{ secrets.APP_INSTALLATION_ID }} \
            --from-literal=github_app_private_key="${{ secrets.APP_KEY }}"

      - name: Install Actions Runner Controller
        run: |
          if helm list --namespace ${{ vars.NAMESPACE }} | grep -q '^arc'; then
            helm upgrade arc ci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller \
            --namespace actions-runner-system  

          else
            helm install arc \
                --namespace "${{ vars.NAMESPACE }}" \
                --create-namespace \
                oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller \
                --set githubConfigSecret=${{ vars.NAMESPACE }} \
                --set syncPeriod=1m
          fi

      - name: Deploy Runner Manifests
        run: kubectl apply -f manifests/*yaml
