name: Deploy Manifests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Kubectl CLI
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Set Kubeconfig Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.13.3

      - name: Install Actions Runner Controller
        run: |
          if helm list --namespace "${{ vars.CONTROL_NAMESPACE }}" | grep -q "^${{ vars.CONTROLLER_INSTALLATION_NAME }}"; then
            helm upgrade "${{ vars.CONTROLLER_INSTALLATION_NAME }}" \
              oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller \
              --namespace "${{ vars.CONTROL_NAMESPACE }}" \
              -f controller/values.yaml
          else
            helm install "${{ vars.CONTROLLER_INSTALLATION_NAME }}" \
              --namespace "${{ vars.CONTROL_NAMESPACE }}" \
              --create-namespace \
              oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller \
              -f controller/values.yaml
          fi      

      - name: Install runners
        run: |
          if helm list --namespace "${{ vars.NAMESPACE }}" | grep -q "^${{ vars.RUNNERS_INSTALLATION_NAME }}"; then
            helm upgrade "${{ vars.RUNNERS_INSTALLATION_NAME }}" \
              --namespace "${{ vars.NAMESPACE }}" \
              --create-namespace \
              oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set \
              -f runners/values.yaml
          else
            helm install "${{ vars.RUNNERS_INSTALLATION_NAME }}" \
              --namespace "${{ vars.NAMESPACE }}" \
              --create-namespace \
              oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set \
              -f runners/values.yaml
          fi

